IMDAPP/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static



urlpatterns = [
#Inward(Consumable)
    path('', views.StockListView.as_view(), name='inventory'),
    path('new', views.StockCreateView.as_view(), name='new-stock'),
    path('stock/<pk>/edit', views.StockUpdateView.as_view(), name='edit-stock'),
    path('stock/<pk>/delete', views.StockDeleteView.as_view(), name='delete-stock'),
    path('stock/<name>', views.StockView.as_view(), name='stockdetails'),

#Inward(NonConsumable)

    path('nonconsumable/', views.NonStockListView.as_view(), name='nonconsumable'),
    path('nonnew', views.NonStockCreateView.as_view(), name='new-nonstock'),
    path('nonstock/<pk>/edit', views.NonStockUpdateView.as_view(), name='edit-nonstock'),
    path('nonstock/<pk>/delete', views.NonStockDeleteView.as_view(), name='delete-nonstock'),
    path('nonstock/<name>', views.NonStockView.as_view(), name='nonstockdetails'),

#Consumer

    path('consumers/', views.ConsumerListView.as_view(), name='consumer-list'),
    # path('consumers/new', views.ConsumerCreateView.as_view(), name='new-consumer'),
    path('consumers/<pk>/edit', views.ConsumerUpdateView.as_view(), name='edit-consumer'),
    path('consumers/<pk>/delete', views.ConsumerDeleteView.as_view(), name='delete-consumer'),
    path('consumers/<name>', views.ConsumerView.as_view(), name='consumer'),

#Supplier

    path('suppliers/', views.SupplierListView.as_view(), name='suppliers-list'),
    path('suppliers/new', views.SupplierCreateView.as_view(), name='new-supplier'),
    path('suppliers/<pk>/edit', views.SupplierUpdateView.as_view(), name='edit-supplier'),
    path('suppliers/<pk>/delete', views.SupplierDeleteView.as_view(), name='delete-supplier'),
    path('suppliers/<name>', views.SupplierView.as_view(), name='supplier'),

#Purchase (Consumable Item)
    path('purchases/', views.PurchaseView.as_view(), name='purchases-list'),
    path('purchases/new', views.SelectConsumerView.as_view(), name='select-consumer'),
    path('purchases/new/<pk>', views.PurchaseCreateView.as_view(), name='new-purchase'),
    path('purchases/<pk>/delete', views.PurchaseDeleteView.as_view(), name='delete-purchase'),
    path("purchases/<billno>", views.PurchaseBillView.as_view(), name='purchase-bill'),
    path("inward/<billno>", views.StockBillView.as_view(), name='inward-bill'),
    path("inwardnc/<billno>", views.NonStockBillView.as_view(), name='inwardnc-bill'),

#Purchase (NonConsumable Item)

    path('nonpurchases/', views.NonPurchaseView.as_view(), name='nonpurchases-list'),
    path('nonpurchases/new', views.SelectSupplierView.as_view(), name='select-supplier'),
    path('nonpurchases/new/<pk>', views.NonPurchaseCreateView.as_view(), name='non-purchase'),
    path('nonpurchases/<pk>/delete', views.NonPurchaseDeleteView.as_view(), name='delete-nonpurchase'),
    path('nonpurchases/<billno>', views.NonPurchaseBillView.as_view(), name='nonpurchase-bill'),

#Slips(Inward,Outward)
    path('outwardslip/', views.outwardslip, name='outwardslip'),
    path('nonoutwardslip/', views.nonoutwardslip, name='nonoutwardslip'),

    # path('nonoutwardslip/', views.nonoutwardslip, name='nonoutwardslip'),
    # path('stockinwardslip/', views.inwardstock, name='stockinwardslip'),
    # path('stocknoninwardslip/', views.noninwardstock, name='stocknoninwardslip'),

    path('inwardslip/', views.inwardslip, name='inwardslip'),
    path('noninwardslip/', views.noninwardslip, name='noninwardslip'),

#ExportAddStockSlip

    path('export/', views.export_csv, name='stockre'),
    path('nonexport/', views.nonexport_csv, name='nonstockre'),

# ExportOurtwardSlip

    path('outwardexport_csv/', views.outwardexport_csv, name='outwardexport_csv'),
    path('outwardnonexport_csv/', views.outwardnonexport_csv, name='outwardnonexport_csv'),

# ExportInwardSlip

    path('hexport/', views.hexport_csv, name='hstockre'),
    path('hnonexport/', views.hexport_csv, name='hnonstockre'),

#Sales (Consumable)

    path('sales/', views.SaleView.as_view(), name='sales-list'),
    path('sales/new', views.SaleCreateView.as_view(), name='new-sale'),
    path('sales/<pk>/delete', views.SaleDeleteView.as_view(), name='delete-sale'),
    path("sales/<billno>", views.SaleBillView.as_view(), name="sale-bill"),

#Sales (NonConsumable)

    path('nonsales/', views.NonSaleView.as_view(), name='nonsales-list'),
    path('nonsales/new', views.NonSaleCreateView.as_view(), name='new-nonsale'),
    path('nonsales/<pk>/delete', views.NonSaleDeleteView.as_view(), name='delete-nonsale'),
    path("nonsales/<billno>", views.NonSaleBillView.as_view(), name="nonsale-bill"),


#Master(Consumable,Nonconsumable)

    path('Master/new',views.addcategory, name='addcategory'),
    path('Master/',views.master,name='master'),
    path('Master/subcategory',views.addsubcategory, name='addsubcategory'),
    path('Master/description',views.adddescription, name='adddescription'),
    path('Master/unit',views.addunit, name='add-unit'),

    path('Master/nonnew', views.addnoncategory, name='addnoncategory'),
    path('Master/nonsubcategory', views.addnonsubcategory, name='addnonsubcategory'),
    path('Master/nondescription', views.addnondescription, name='addnondescription'),

#Classified Category,subcategory and description
    path('subcategorys', views.subcategorys, name="subcategorys"),
    path('descriptions', views.descriptions, name="descriptions"),
    path('nonsubcategorys', views.nonsubcategorys, name="nonsubcategorys"),
    path('nondescriptions', views.nondescriptions, name="nondescriptions"),



#Gstin verify
    path('verify',views.my_form,name="gstin"),
    path("gstverify",views.gstverify,name='gstver'),
    path("gstverify1",views.gstverify1,name='gstver1'),
    path("gstverifyc",views.gst,name='gst'),
    path("gstverifyc1",views.gst1,name='gst1'),


#inward History
    path("inwardhistory",views.inwardHistory),
    path("noninwardhistory",views.noninwardHistory),

# InwardHistoryBill
    path("inwardhistory/<billno>", views.HStockBillView.as_view(), name='hinward-bill'),
    path("noninwardhistory/<billno>", views.NONHStockBillView.as_view(), name='nonhinward-bill'),

# inwardSlipHistory
    path("inwardsliphistory", views.inwardsliphistory, name='inwardhistory'),
    path("noninwardsliphistory", views.noninwardsliphistory, name='noninwardhistory'),

#History
    path('historypage/', views.get_trs, name="trs"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

IMDPROJ/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [

    path('admin/', admin.site.urls, name='admin'),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('', include('homepage.urls')),
    path('inventory/', include('IMDAPP.urls')),

]
# urlpatterns +=staticfiles_urlpatterns()

IMDAPP/models.py
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.

## History Table

class trs(models.Model):
    kdno=models.CharField(max_length=255)
    sors_sink=models.CharField(max_length=255)
    ref1=models.CharField(max_length=255)
    ref2=models.CharField(max_length=255)
    ref3=models.CharField(max_length=255)
    unit_cost=models.CharField(max_length=255)
    iss_srs=models.IntegerField()
    trs_type=models.IntegerField()
    qty_trs=models.DecimalField(blank=True, null=True, max_digits=20,  decimal_places=10)
    balance=models.DecimalField(blank=True, null=True, max_digits=20,  decimal_places=10)

    def __str__(self):
        return self.kdno

    class Meta:
        db_table = 'trs'

#CATEGORY

class Category(models.Model):
    category=models.CharField(max_length=255)

    def __str__(self):
        return self.category

    class Meta:
        db_table = 'Category'


# SUBCATEGORY

class Subcategory(models.Model):
    subcategory=models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_consumable=models.BooleanField(default=False)


    def __str__(self):
        return self.subcategory

    class Meta:
        db_table = 'Subcategory'


# DESCRIPTION

class Description(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    description=models.TextField(max_length=255)

    def __str__(self):
        return self.description

    class Meta:
        db_table = 'Description'


# SUPPLIER

class Supplier(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    phone = models.CharField(max_length=12,unique=True)
    address = models.TextField()
    email = models.EmailField(max_length=100)
    gstin = models.CharField(max_length=15, unique=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'Supplier'

# CONSUMER


class Consumer(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    phone = models.CharField(max_length=12 ,unique=True)
    address = models.TextField()
    email = models.EmailField(max_length=100)
    gstin = models.CharField(max_length=15, unique=True)
    is_deleted = models.BooleanField(default=False)


    def __str__(self):
        return str(self.name)

    class Meta:
        db_table = 'Consumer'


# UNIT
class Unit(models.Model):
    unit = models.CharField(max_length=20)

    def __str__(self):
        return self.unit

    class Meta:
        db_table = 'Unit'
# STOCK

class Stock(models.Model):

    CONDITION = [
        ('GOOD', 'GOOD'),
        ('TORN', 'TORN'),
        ('DAMAGED', 'DAMAGED'),
    ]
    # MODE_OF_DELIVERY = [
    #     ('BY-HAND', 'BY-HAND'),
    #     ('COURIER', 'COURIER'),
    #     ('OTHER', 'OTHER'),
    #
    # ]

    billno = models.AutoField(primary_key=True)
    time = models.DateTimeField(auto_now=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    subcategory=models.ForeignKey(Subcategory,on_delete=models.CASCADE)
    description=models.ForeignKey(Description,on_delete=models.CASCADE)
    name=models.ForeignKey(Consumer,on_delete=models.CASCADE)
    unit=models.ForeignKey(Unit,on_delete=models.CASCADE)
    Mode_of_delivery = models.CharField(max_length=50)
    # Mode_of_delivery = models.CharField(max_length=24, choices=MODE_OF_DELIVERY, default=MODE_OF_DELIVERY)
    label_code = models.CharField(max_length=50, default="")
    condition = models.CharField(max_length=50, choices=CONDITION)
    quantity = models.IntegerField(default=1)
    perprice = models.IntegerField(default=1)
    totalprice = models.IntegerField(default=1)
    is_deleted = models.BooleanField(default=False)





    def __str__(self):
        return  str(self.subcategory) +   " \n ,Label code=" + str(self.label_code)  +   "\n ,Description=" + str(self.description)


    def get_items_list(self):
        return Stock.objects.filter(billno=self)

    def total(self):
        totalprice = 0
        totalprice = self.quantity * self.perprice
        return totalprice

    class Meta:
        db_table = 'Stock'


# INWARD STOCK

class InwardBillDetails(models.Model):
    billno = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name='inwarddetailsbillno')
    total = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return "Bill no: " + str(self.billno.billno)

    class Meta:
        db_table = 'InwardBillDetails'

#nonconsumable

# Category

class NonCategory(models.Model):
    category=models.CharField(max_length=255)
    def __str__(self):
        return self.category

    class Meta:
        db_table = 'NonCategory'

# Subcategory

class NonSubcategory(models.Model):
    subcategory=models.CharField(max_length=255)
    category = models.ForeignKey(NonCategory, on_delete=models.CASCADE)
    is_consumable=models.BooleanField(default=False)
    def __str__(self):
        return self.subcategory

    class Meta:
        db_table = 'NonSubcategory'

# Description

class NonDescription(models.Model):
    category = models.ForeignKey(NonCategory, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(NonSubcategory, on_delete=models.CASCADE)
    description=models.TextField(max_length=255)

    def __str__(self):
        return self.description

    class Meta:
        db_table = 'NonDescription'
#




# NON-CONSUMABLE STOCK

class NonStock(models.Model):

    CONDITION = [
        ('GOOD', 'GOOD'),
        ('TORN', 'TORN'),
        ('DAMAGED', 'DAMAGED'),
    ]
    # MODE_OF_DELIVERY = [
    #     ('BY-HAND', 'BY-HAND'),
    #     ('COURIER', 'COURIER'),
    #     ('OTHER', 'OTHER'),
    #
    # ]
    billno = models.AutoField(primary_key=True)
    time = models.DateTimeField(auto_now=True)
    category=models.ForeignKey(NonCategory,on_delete=models.CASCADE)
    subcategory=models.ForeignKey(NonSubcategory,on_delete=models.CASCADE)
    description=models.ForeignKey(NonDescription,on_delete=models.CASCADE)
    name=models.ForeignKey(Supplier,on_delete=models.CASCADE)
    unit=models.ForeignKey(Unit,on_delete=models.CASCADE)
    Mode_of_delivery = models.CharField(max_length=50)  # received by
    label_code = models.CharField(max_length=50, default="")
    condition = models.CharField(max_length=50, choices=CONDITION)
    quantity = models.IntegerField(default=1)
    perprice = models.IntegerField(default=1)
    totalprice = models.IntegerField(default=1)
    is_deleted = models.BooleanField(default=False)



    def __str__(self):
        return  str(self.subcategory) +   " ,Label code=" + str(self.label_code)  +   " ,Description=" + str(self.description)


    def get_items_list(self):
        return NonStock.objects.filter(billno=self)

    def total(self):
        totalprice = 0
        totalprice = self.quantity * self.perprice
        return totalprice

    class Meta:
        db_table = 'NonStock'


# NON-CONSUMABLE INWARD BILL

class NonInwardBillDetails(models.Model):
    billno = models.ForeignKey(NonStock, on_delete=models.CASCADE, related_name='noninwarddetailsbillno')
    total = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return "Bill no: " + str(self.billno.billno)

    class Meta:
        db_table = 'NonInwardBillDetails'

# ADD ITEM BILL

class PurchaseBill(models.Model):
    billno = models.AutoField(primary_key=True)
    time = models.DateTimeField(auto_now=True)
    consumer = models.ForeignKey(Consumer, on_delete=models.CASCADE, related_name='purchasesupplier')

    def __str__(self):
        return "Bill no: " + str(self.billno)

    def get_items_list(self):
        return PurchaseItem.objects.filter(billno=self)

    def get_total_price(self):
        purchaseitems = PurchaseItem.objects.filter(billno=self)
        total = 0
        for item in purchaseitems:
            total += item.totalprice
        return total

    class Meta:
        db_table = 'PurchaseBill'
# ADD ITEM BILL DETAILS

class PurchaseBillDetails(models.Model):
    billno = models.ForeignKey(PurchaseBill, on_delete=models.CASCADE, related_name='purchasedetailsbillno')
    total = models.CharField(max_length=50, blank=True, null=True)
    is_deleted=models.BooleanField(default=False)

    def __str__(self):
        return "Bill no: " + str(self.billno.billno)

    class Meta:
        db_table = 'PurchaseBillDetails'

# ADD INWARD ITEM

class PurchaseItem(models.Model):
    billno = models.ForeignKey(PurchaseBill, on_delete=models.CASCADE, related_name='purchasebillno')
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name='purchaseitem')
    quantity = models.IntegerField(default="")
    perprice = models.IntegerField(default="")
    totalprice = models.IntegerField(default="")
    is_deleted=models.BooleanField(default=False)

    def __str__(self):
        return "Bill no: " + str(self.billno.billno) + ", Item = " + str(self.stock.subcategory)

    class Meta:
        db_table = 'PurchaseItem'


#nonconsumable BILL
class NonPurchaseBill(models.Model):
    billno = models.AutoField(primary_key=True)
    time = models.DateTimeField(auto_now=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, related_name='nonpurchasesupplier')

    def __str__(self):
        return "Bill no: " + str(self.billno)

    def get_items_list(self):
        return NonPurchaseItem.objects.filter(billno=self)

    def get_total_price(self):
        nonpurchaseitems = NonPurchaseItem.objects.filter(billno=self)
        total = 0
        for item in nonpurchaseitems:
            total += item.totalprice
        return total

    class Meta:
        db_table = 'NonPurchaseBill'



class NonPurchaseBillDetails(models.Model):

IMDAPP/templates/purchases/delete_nonpurchase.html
{% extends "base.html" %}


{% block title %} Delete Inward {% endblock title %}


{% block content %}
                
    <form method="post">
        
        {% csrf_token %}
        
        <fieldset class="form-group" style="font-family: 'Alkalami'">
            <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">Delete Inward Bill</div> <br>
            <h2 style="color:#575757;">Are you sure you want to delete the Inward Bill No: {{ object.billno }}?</h2>
        </fieldset>

        <div class="form-group" style="font-family: 'Alkalami'">
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
            <a href="{% url 'nonpurchases-list' %}" class="btn btn-secondary">Cancel</a>
        </div>
        
    </form>

{% endblock content %}

IMDAPP/templates/purchases/delete_purchase.html
{% extends "base.html" %}


{% block title %} Delete Inward {% endblock title %}


{% block content %}
                
    <form method="post">
        
        {% csrf_token %}
        
        <fieldset class="form-group" style="font-family: 'Alkalami'">
            <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">Delete Inward Bill</div> <br>
            <h2 style="color:#575757;">Are you sure you want to delete the Inward Bill No: {{ object.billno }}?</h2>
        </fieldset>

        <div class="form-group" style="font-family: 'Alkalami'">
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
            <a href="{% url 'purchases-list' %}" class="btn btn-secondary">Cancel</a>
        </div>

    </form>

{% endblock content %}

IMDAPP/templates/purchases/new_purchase.html
{% extends "base.html" %}
{% load static %}
<!--{% include "homepage/messages.html"%}-->

{% block title %} Add Item {% endblock title %}


{% block content %}
  <div class="card text-left">
      <div class="card-header" style="background-color:#01345B">
        <div class="row" style="color: white; font-style: bold; font-size: 3.5rem">
        <div class="col-md-8" style="font-family: 'Alkalami'" >Inward Items</div>
       <div class="col-md-4">
            </div>
    </div>
      </div>
      <div class="card-body" style="font-family: 'Alkalami'">

<!--    <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">New Purchase</div>-->

        <br><!-- Log on to codeastro.com for more projects -->

        <div class="panel panel-default">
            <div class="panel-heading panel-heading-text">Supplier Details</div>
            <div class="panel-body">

                <div class="form-group">
                    <label for="id_name" class="panel-body-text">Supplier Name:</label>
                    <input type="text" class="form-control textinput" id="id_name" value="{{ consumer.name }}" disabled>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_phone" class="panel-body-text">Phone No:</label>
                        <input type="text" class="form-control textinput" id="id_phone" value="{{ consumer.phone }}" disabled>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="id_gstin" class="panel-body-text">GSTIN No:</label>
                        <input type="gstin" class="form-control textinput" id="id_gstin" value="{{ consumer.gstin }}" disabled>
                    </div>
                </div>

            </div><!-- Log on to codeastro.com for more projects -->
        </div>

        <br>

        <form method="post" class="panel panel-default">

            {% csrf_token %}
            {{ formset.management_form }}

            <div class="panel-heading panel-heading-text">Product Details</div>

                <div id="stockitem">
                    <div class="panel-body">
                    {% for form in formset %}
                        <div class="row form-row">
                            <div class="form-group col-md-4">
                                {{ form.stock.errors }}
                                <label class="panel-body-text">Stock:</label>
                                {{ form.stock }}
                            </div><!-- Log on to codeastro.com for more projects -->
                            <div class="form-group col-md-3">
                                <label class="panel-body-text"  value="1">Price per item:</label>
                                {{ form.perprice }}
                            </div>
                            <div class="form-group col-md-3">
                                {{ form.quantity.errors }}
                                <label class="panel-body-text" >Quantity:</label>
                                {{ form.quantity }}
                            </div>
                            <div class="form-group col-md-2">
                                <label class="panel-body-text">Price:</label>
                                <input type="text" class="textinput form-control totalprice" disabled required>
                            </div>
<!--                            <div class="form-group col-md-2">-->
<!--                                <label class="panel-body-text" style="color: #000">.</label>-->
<!--                                <button class="form-control btn btn-danger remove-form-row">Delete</button>-->
<!--                            </div>-->
                        </div>
                    {% endfor %}
<!--                        <div style="text-align: right;">-->
<!--                            <a href="#" class="add-form-row">+ Add More</a>-->
<!--                        </div>-->
                    </div>
                </div>


            <br><!-- Log on to codeastro.com for more projects -->

            <div class="align-middle">
                <button type="submit" class="btn btn-info">Add Item</button>
                <a href="{% url 'select-supplier' %}" class="btn btn-danger">Go Back</a>
<!--                <a href="{% url 'purchases-list' %}" class="btn btn-secondary">Next</a>-->
            </div>

        </form>
      </div>
    </div>
  </div>
    <!-- Custom JS to add and remove item forms --><!-- Log on to codeastro.com for more projects -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dialogbox.js' %}"></script>
<!--    <script src="script.js"></script>-->
    <script type="text/javascript">

        //creates custom alert object
        var custom_alert = new custom_alert();

        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }

        //stores the total no of item forms
        var total = 1;

        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            //var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
            newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
                var name = $(this).attr('name')
                if(name) {
                    name = name.replace('-' + (total-1) + '-', '-' + total + '-');
                    var id = 'id_' + name;
                    $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
                }
            });
            newElement.find('label').each(function() {
                var forValue = $(this).attr('for');
                if (forValue) {
                forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
                $(this).attr({'for': forValue});
                }
            });
            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            return false;
        }

        function deleteForm(prefix, btn) {
            //var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1){
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i=0, formCount=forms.length; i<formCount; i++) {
                    $(forms.get(i)).find(':input').each(function() {
                        updateElementIndex(this, prefix, i);
                    });
                }
                total--;
            } else {
                custom_alert.render("Field cannot be deleted");
            }
            return false;
        }

        $(document).on('click', '.add-form-row', function(e){
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });

        $(document).on('click', '.remove-form-row', function(e){
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });


        //updates the total price by multiplying 'price per item' and 'quantity'
        $(document).on('change', '.setprice', function(e){
            e.preventDefault();
            //gets the values
            var element = $(this);
            var quantity = element.parents('.form-row').find('.quantity').val();
            var perprice = element.parents('.form-row').find('.price').val();
            //calculates the total
            var tprice = quantity * perprice;
            //sets it to field
            element.parents('.form-row').find('.totalprice').val(tprice);
            return false;
        });

    </script>

{% endblock content %}

IMDAPP/templates/purchases/select_consumer.html
{% extends "base.html" %}


{% block title %} Select Supplier {% endblock title %}


{% block content %}

    <div class="card text-left">
      <div class="card-header" style="background-color:#01345B">
        <div class="row" style="color: white; font-style: bold; font-size: 3.5rem">
            <div class="col-md-8" style="font-family: 'Alkalami'" >Add Item</div>
                <div class="col-md-4">
                    <div style="float:right; margin-top:8%"> <a class="btn  btn-info" href="{% url 'gstver' %}">New Supplier</a>

                </div>
            </div>

        </div>
      </div>

    <br>
  <div class="card-body" style="font-family: 'Alkalami'">
    <form method="post">
        <label for="id_consumer">Supplier:</label>
        {% csrf_token %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ supplier.label_tag }}
                {{ field }}
            </div>
        {% endfor %}

        <br>
        <div class="align-middle">
            <button type="submit" class="btn btn-success">Next</button>
        </div>

    </form>
    </div>
    </div>
{% endblock content %}

IMDAPP/templates/purchases/select_supplier.html
{% extends "base.html" %}


{% block title %} Select Supplier {% endblock title %}


{% block content %}

    <div class="card text-left">
      <div class="card-header" style="background-color:#01345B">
        <div class="row" style="color: white; font-style: bold; font-size: 3.5rem">
            <div class="col-md-8" style="font-family: 'Alkalami'" >Add Item</div>
                <div class="col-md-4">
                    <div style="float:right; margin-top:8%">
            <a class="btn  btn-info" href="{% url 'gstver1' %}">New Supplier</a>

                </div>
            </div>

        </div>
      </div>

    <br>
  <div class="card-body" style="font-family: 'Alkalami'">
    <form method="post">

        {% csrf_token %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}

        <br>
        <div class="align-middle">
            <button type="submit" class="btn btn-success">Next</button>
        </div>

    </form>
    </div>
    </div>
{% endblock content %}